<?php

use Fisharebest\Webtrees\I18N;

?>
<script type="javascript/template" id="faces-attach-modal-template">
    <div class="modal fade" tabindex="-1" id="faces-attach-modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <p><?= I18N::translate('Enter individuals id or something else') ?>:</p>
                    <?= view('components/select-individual', ['name' => 'faces-attach-pid', 'tree' => $tree]) ?>
                </div>
                <div class="modal-footer">
                    <button id="faces-attach-button" class="btn btn-primary">
                        <?= I18N::translate('Add') ?>
                    </button>
                    <button class="btn btn-secondary" data-dismiss="modal">
                        <?= I18N::translate('Cancel') ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</script>
<script type="javascript/template" id="faces-detach-modal-template">
    <div class="modal fade" tabindex="-1" id="faces-detach-modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <p>
                        <?= I18N::translate('Are you sure that want delete %s from image?', '<strong>{%=o.name%}</strong>') ?>
                    </p>
                    <p class="text-danger">
                        <?= I18N::translate('This operation can not be undone') ?>.
                    </p>
                    <?php if ($settings['linking']) : ?>
                        <p class="text-danger">
                            (!) <?= I18N::translate('You have enabled "Create links" feature') ?>.<br />
                            (!) <?= I18N::translate('Linked individuals will not be detached from media') ?>.
                        </p>
                    <?php endif ?>
                </div>
                <div class="modal-footer">
                    <button id="faces-detach-button" class="btn btn-primary">
                        <?= I18N::translate('Delete') ?>
                    </button>
                    <button class="btn btn-secondary" data-dismiss="modal">
                        <?= I18N::translate('Cancel') ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</script>
<script type="javascript/template" id="faces-tooltip-template">
    <div class="faces-tooltip-wrapper">
        <p class="faces-tooltip-name">{%=o.person.name%}</p>
        <p class="faces-tooltip-life">
            {%=o.person.age%}<br />
            {%=o.person.life%}
        </p>
    </div>
</script>
<script type="javascript/template" id="faces-person-template">
    <span class="faces-person-wrapper">
        {% if (o.link !== '#') { %}
        <a href="{%=o.link%}"
           data-pid="{%=o.person.pid%}"
           data-key="{%=o.key%}"
           class="faces-person-name">{%=o.person.name%}</a>
        {% } else { %}
        <span data-pid="{%=o.person.pid%}"
              data-key="{%=o.key%}"
              class="faces-person-name">{%=o.person.name%}</span>
        {% } %}
        {% if (o.edit) { %}
        <span class="faces-person-detach"
              data-pid="{%=o.person.pid%}"
              data-name="{%=o.person.name%}">(&times;)</span>
        {% } %}
    </span>
</script>
