<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

?>

<?= view('components/breadcrumbs', ['links' => $breadcrumbs]) ?>

<div id="faces-admin-config">

    <div id="faces-admin-config-actions" class="float-end">
        <?php if (!empty($filters)) : ?>
            <a class="btn btn-light" href="<?= e($routes['admin']) ?>">
                <?= I18N::translate('Reset filters') ?>
            </a>
        <?php endif ?>
        <div class="btn-group">
            <span class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown" id="faces-missed-menu">
                <?= I18N::translate('Missed') ?>
            </span>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="faces-missed-menu">
                <span class="dropdown-item text-right text-danger"
                      title="<?= I18N::translate('Remove all records without media') ?>"
                      data-action="missed-delete"
                      data-url="<?= e($routes['missed_destroy']) ?>">
                    <?= I18N::translate('Remove') ?>
                    <i class="far fa-trash-alt fa-fw"></i>
                </span>
                <span class="dropdown-item text-right text-success"
                      title="<?= I18N::translate('Try to find missed records by filename') ?>"
                      data-action="missed-repair"
                      data-url="<?= e($routes['missed_repair']) ?>">
                    <?= I18N::translate('Find') ?>
                    <i class="fas fa-magic fa-fw"></i>
                </span>
            </div>
        </div>
        <div class="btn-group">
            <span class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown" id="faces-settings-menu">
                <?= I18N::translate('Settings') ?>
            </span>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="faces-settings-menu">
                <?php foreach ([
                    [
                        'key' => 'exif',
                        'state' => $settings['exif'],
                        'route' => $routes['setting_exif'],
                        'name' => 'Read XMP data',
                        'title' => 'Read and show XMP data (such as Goggle Picasa face tags) from media file',
                    ],
                    [
                        'key' => 'linking',
                        'state' => $settings['linking'],
                        'route' => $routes['setting_linking'],
                        'name' => 'Create links',
                        'title' => 'Link individual with media when mark them on photo',
                    ],
                    [
                        'key' => 'meta',
                        'state' => $settings['meta'],
                        'route' => $routes['setting_meta'],
                        'name' => 'Show meta',
                        'title' => 'Load and show information from linked fact',
                    ],
                    [
                        'key' => 'note',
                        'state' => $settings['note'],
                        'route' => $routes['setting_note'],
                        'name' => 'Show note',
                        'title' => 'Load and show information from note',
                    ],
                    [
                        'key' => 'tab',
                        'state' => $settings['tab'],
                        'route' => $routes['setting_tab'],
                        'name' => 'Show tab',
                        'title' => 'Show tab on individuals page',
                    ],
                ] as $item) : ?>
                    <span class="dropdown-item text-right" title="<?= I18N::translate($item['title']) ?>">
                    <span class="form-switch">
                        <input type="checkbox"
                               class="form-check-input"
                               id="faces-<?= e($item['key']) ?>-state"
                               data-action="setting-<?= e($item['key']) ?>"
                               data-url="<?= e($item['route']) ?>"
                             <?= $item['state'] ? 'checked' : '' ?>>
                        <label class="form-check-label" for="faces-<?= e($item['key']) ?>-state"><?= I18N::translate($item['name']) ?></label>
                    </span>
                </span>
                <?php endforeach ?>
            </div>
        </div>
    </div>

    <h1><?= $title ?></h1>

    <table id="faces-admin-config-table" class="table" data-url="<?= e($routes['data']) ?>"
           data-length-menu="<?= e(json_encode([[10, 20, 50, 100, 500, 1000, -1], [I18N::number(10), I18N::number(20), I18N::number(50), I18N::number(100), I18N::number(500), I18N::number(1000), I18N::translate('All')]])) ?>"
           data-language="<?= e(json_encode([
               'paginate'       => [
                   /* I18N: A button label, first page */
                   'first'    => I18N::translate('first'),
                   /* I18N: A button label, last page */
                   'last'     => I18N::translate('last'),
                   /* I18N: A button label, next page */
                   'next'     => I18N::translate('next'),
                   /* I18N: A button label, previous page */
                   'previous' => I18N::translate('previous'),
               ],
               'emptyTable'     => I18N::translate('No records to display'),
               /* I18N: %s are placeholders for numbers */
               'info'           => I18N::translate('Showing %1$s to %2$s of %3$s', '_START_', '_END_', '_TOTAL_'),
               'infoEmpty'      => I18N::translate('Showing %1$s to %2$s of %3$s', I18N::number(0), I18N::number(0), I18N::number(0)),
               /* I18N: %s is a number */
               'infoFiltered'   => I18N::translate('(filtered from %s total entries)', '_MAX_'),
               /* I18N: %s is a number of records per page */
               'lengthMenu'     => I18N::translate('Display %s', '_MENU_'),
               'loadingRecords' => I18N::translate('Loading…'),
               'processing'     => I18N::translate('Calculating…'),
               'search'         => I18N::translate('Filter'),
               'zeroRecords'    => I18N::translate('No records to display'),
           ])) ?>">
        <thead>
        <tr>
            <th><?= I18N::translate('Media') ?></th>
            <th><?= I18N::translate('Notes') ?></th>
            <th class="text-center"><?= I18N::translate('Status') ?></th>
            <th class="text-right"><?= I18N::translate('Actions') ?></th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>

</div>

<?php View::push('javascript') ?>
<script type="application/javascript">
    window.WT_FACES_WARNING = '<?= I18N::translate('Are you sure?') ?>\n<?= e(I18N::translate('This operation can not be undone')) ?>.'
</script>
<script type="javascript/template" id="faces-alert-template">
    <div class="alert alert-info alert-dismissible">
        {%=o.message%}
        {% if (o.readmore) { %}
        <a href="{%=o.readmore%}" target="_blank"><?= I18N::translate('Read more') ?>...</a>
        {% } %}
        <span class="close" data-dismiss="alert">&times;</span>
    </div>
</script>
<?php foreach ($scripts as $path) : ?>
    <script type="text/javascript" src="<?= $path ?>"></script>
<?php endforeach ?>
<?php View::endpush() ?>

<?php View::push('styles') ?>
<?php foreach ($styles as $path) : ?>
    <link rel="stylesheet" href="<?= $path ?>">
<?php endforeach ?>
<?php View::endpush() ?>
